In [2]:
import pandas as pd

In [3]:
import numpy as np


In [4]:
!pip install sklearn#import ML library

ERROR: Invalid requirement: 'sklearn#import'


In [5]:
csv_import=pd.read_csv("HousePrices.csv")# import csv file from the file directory

In [6]:
csv_import

Id  Dwell_Type Zone_Class  LotFrontage  LotArea Road_Type Alley  \
0       1          60         RL         65.0     8450      Pave   NaN   
1       2          20         RL         80.0     9600      Pave   NaN   
2       3          60         RL         68.0    11250      Pave   NaN   
3       4          70         RL         60.0     9550      Pave   NaN   
4       5          60         RL         84.0    14260      Pave   NaN   
...   ...         ...        ...          ...      ...       ...   ...   
2068  942          60         RL          NaN     8755      Pave   NaN   
2069  943          90         RL         63.0     7711      Pave   NaN   
2070  944          90         RL        313.0    25000      Pave   NaN   
2071  945          20         RL         52.0    14375      Pave   NaN   
2072  946          50         RM         98.0     8820      Pave   NaN   

     Property_Shape LandContour Utilities  ... PoolArea PoolQC  Fence  \
0               Reg         Lvl    AllPub  ...        0    NaN    NaN   
1               Reg         Lvl    AllPub  ...        0    NaN    NaN   
2               IR1         Lvl    AllPub  ...        0    NaN    NaN   
3               IR1         Lvl    AllPub  ...        0    NaN    NaN   
4               IR1         Lvl    AllPub  ...        0    NaN    NaN   
...             ...         ...       ...  ...      ...    ...    ...   
2068            IR1         Lvl    AllPub  ...        0    NaN  GdPrv   
2069            IR1         Lvl    AllPub  ...        0    NaN    NaN   
2070            Reg         Low    AllPub  ...        0    NaN    NaN   
2071            IR1         Lvl    NoSeWa  ...        0    NaN    NaN   
2072            Reg         Lvl    AllPub  ...        0    NaN   MnWw   

     MiscFeature MiscVal MoSold YrSold  SaleType  SaleCondition  \
0            NaN       0      2   2008        WD         Normal   
1            NaN       0      5   2007        WD         Normal   
2            NaN       0      9   2008        WD         Normal   
3            NaN       0      2   2006        WD        Abnorml   
4            NaN       0     12   2008        WD         Normal   
...          ...     ...    ...    ...       ...            ...   
2068         NaN       0      6   2009        WD         Normal   
2069         NaN       0      8   2007       Oth        Abnorml   
2070         NaN       0      6   2007        WD         Normal   
2071         NaN       0      1   2009       COD        Abnorml   
2072         NaN       0      9   2009        WD         Normal   

      Property_Sale_Price  
0                  208500  
1                  181500  
2                  223500  
3                  140000  
4                  250000  
...                   ...  
2068               214000  
2069               150000  
2070               143000  
2071               137500  
2072               124900  

[2073 rows x 81 columns]

In [7]:
csv_import.isnull().sum()#check for th null values

Id                       0
Dwell_Type               0
Zone_Class               0
LotFrontage            320
LotArea                  0
                      ... 
MoSold                   0
YrSold                   0
SaleType                 0
SaleCondition            0
Property_Sale_Price      0
Length: 81, dtype: int64

In [8]:
a=csv_import.columns[csv_import.isnull().any()]
csv_import[a].isnull().sum()
# to view all the null values in the data

LotFrontage      320
Alley           1944
MasVnrType        14
MasVnrArea        14
BsmtQual          59
BsmtCond          59
BsmtExposure      61
BsmtFinType1      59
BsmtFinType2      60
Electrical         1
FireplaceQu      988
GarageType       113
GarageYrBlt      113
GarageFinish     113
GarageQual       113
GarageCond       113
PoolQC          2065
Fence           1669
MiscFeature     1993
dtype: int64

In [9]:
csv_import.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2073 entries, 0 to 2072
Data columns (total 81 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Id                   2073 non-null   int64  
 1   Dwell_Type           2073 non-null   int64  
 2   Zone_Class           2073 non-null   object 
 3   LotFrontage          1753 non-null   float64
 4   LotArea              2073 non-null   int64  
 5   Road_Type            2073 non-null   object 
 6   Alley                129 non-null    object 
 7   Property_Shape       2073 non-null   object 
 8   LandContour          2073 non-null   object 
 9   Utilities            2073 non-null   object 
 10  LotConfig            2073 non-null   object 
 11  LandSlope            2073 non-null   object 
 12  Neighborhood         2073 non-null   object 
 13  Condition1           2073 non-null   object 
 14  Condition2           2073 non-null   object 
 15  Dwelling_Type        2073 non-null   o

In [10]:
#fill up the null values by the mean

In [11]:
csv_import["LotFrontage"].fillna((csv_import["LotFrontage"].mean()),inplace=True)
csv_import
#LotFrontage null values filled with mean

Id  Dwell_Type Zone_Class  LotFrontage  LotArea Road_Type Alley  \
0       1          60         RL    65.000000     8450      Pave   NaN   
1       2          20         RL    80.000000     9600      Pave   NaN   
2       3          60         RL    68.000000    11250      Pave   NaN   
3       4          70         RL    60.000000     9550      Pave   NaN   
4       5          60         RL    84.000000    14260      Pave   NaN   
...   ...         ...        ...          ...      ...       ...   ...   
2068  942          60         RL    72.056475     8755      Pave   NaN   
2069  943          90         RL    63.000000     7711      Pave   NaN   
2070  944          90         RL   313.000000    25000      Pave   NaN   
2071  945          20         RL    52.000000    14375      Pave   NaN   
2072  946          50         RM    98.000000     8820      Pave   NaN   

     Property_Shape LandContour Utilities  ... PoolArea PoolQC  Fence  \
0               Reg         Lvl    AllPub  ...        0    NaN    NaN   
1               Reg         Lvl    AllPub  ...        0    NaN    NaN   
2               IR1         Lvl    AllPub  ...        0    NaN    NaN   
3               IR1         Lvl    AllPub  ...        0    NaN    NaN   
4               IR1         Lvl    AllPub  ...        0    NaN    NaN   
...             ...         ...       ...  ...      ...    ...    ...   
2068            IR1         Lvl    AllPub  ...        0    NaN  GdPrv   
2069            IR1         Lvl    AllPub  ...        0    NaN    NaN   
2070            Reg         Low    AllPub  ...        0    NaN    NaN   
2071            IR1         Lvl    NoSeWa  ...        0    NaN    NaN   
2072            Reg         Lvl    AllPub  ...        0    NaN   MnWw   

     MiscFeature MiscVal MoSold YrSold  SaleType  SaleCondition  \
0            NaN       0      2   2008        WD         Normal   
1            NaN       0      5   2007        WD         Normal   
2            NaN       0      9   2008        WD         Normal   
3            NaN       0      2   2006        WD        Abnorml   
4            NaN       0     12   2008        WD         Normal   
...          ...     ...    ...    ...       ...            ...   
2068         NaN       0      6   2009        WD         Normal   
2069         NaN       0      8   2007       Oth        Abnorml   
2070         NaN       0      6   2007        WD         Normal   
2071         NaN       0      1   2009       COD        Abnorml   
2072         NaN       0      9   2009        WD         Normal   

      Property_Sale_Price  
0                  208500  
1                  181500  
2                  223500  
3                  140000  
4                  250000  
...                   ...  
2068               214000  
2069               150000  
2070               143000  
2071               137500  
2072               124900  

[2073 rows x 81 columns]

In [12]:
csv_import["MasVnrArea"].fillna((csv_import["MasVnrArea"].mean()),inplace=True)
csv_import
#MasVnrArea filled null values with mean

Id  Dwell_Type Zone_Class  LotFrontage  LotArea Road_Type Alley  \
0       1          60         RL    65.000000     8450      Pave   NaN   
1       2          20         RL    80.000000     9600      Pave   NaN   
2       3          60         RL    68.000000    11250      Pave   NaN   
3       4          70         RL    60.000000     9550      Pave   NaN   
4       5          60         RL    84.000000    14260      Pave   NaN   
...   ...         ...        ...          ...      ...       ...   ...   
2068  942          60         RL    72.056475     8755      Pave   NaN   
2069  943          90         RL    63.000000     7711      Pave   NaN   
2070  944          90         RL   313.000000    25000      Pave   NaN   
2071  945          20         RL    52.000000    14375      Pave   NaN   
2072  946          50         RM    98.000000     8820      Pave   NaN   

     Property_Shape LandContour Utilities  ... PoolArea PoolQC  Fence  \
0               Reg         Lvl    AllPub  ...        0    NaN    NaN   
1               Reg         Lvl    AllPub  ...        0    NaN    NaN   
2               IR1         Lvl    AllPub  ...        0    NaN    NaN   
3               IR1         Lvl    AllPub  ...        0    NaN    NaN   
4               IR1         Lvl    AllPub  ...        0    NaN    NaN   
...             ...         ...       ...  ...      ...    ...    ...   
2068            IR1         Lvl    AllPub  ...        0    NaN  GdPrv   
2069            IR1         Lvl    AllPub  ...        0    NaN    NaN   
2070            Reg         Low    AllPub  ...        0    NaN    NaN   
2071            IR1         Lvl    NoSeWa  ...        0    NaN    NaN   
2072            Reg         Lvl    AllPub  ...        0    NaN   MnWw   

     MiscFeature MiscVal MoSold YrSold  SaleType  SaleCondition  \
0            NaN       0      2   2008        WD         Normal   
1            NaN       0      5   2007        WD         Normal   
2            NaN       0      9   2008        WD         Normal   
3            NaN       0      2   2006        WD        Abnorml   
4            NaN       0     12   2008        WD         Normal   
...          ...     ...    ...    ...       ...            ...   
2068         NaN       0      6   2009        WD         Normal   
2069         NaN       0      8   2007       Oth        Abnorml   
2070         NaN       0      6   2007        WD         Normal   
2071         NaN       0      1   2009       COD        Abnorml   
2072         NaN       0      9   2009        WD         Normal   

      Property_Sale_Price  
0                  208500  
1                  181500  
2                  223500  
3                  140000  
4                  250000  
...                   ...  
2068               214000  
2069               150000  
2070               143000  
2071               137500  
2072               124900  

[2073 rows x 81 columns]

In [13]:
property_data=pd.DataFrame(csv_import)#convert the csv into DF

In [14]:
property_data

Id  Dwell_Type Zone_Class  LotFrontage  LotArea Road_Type Alley  \
0       1          60         RL    65.000000     8450      Pave   NaN   
1       2          20         RL    80.000000     9600      Pave   NaN   
2       3          60         RL    68.000000    11250      Pave   NaN   
3       4          70         RL    60.000000     9550      Pave   NaN   
4       5          60         RL    84.000000    14260      Pave   NaN   
...   ...         ...        ...          ...      ...       ...   ...   
2068  942          60         RL    72.056475     8755      Pave   NaN   
2069  943          90         RL    63.000000     7711      Pave   NaN   
2070  944          90         RL   313.000000    25000      Pave   NaN   
2071  945          20         RL    52.000000    14375      Pave   NaN   
2072  946          50         RM    98.000000     8820      Pave   NaN   

     Property_Shape LandContour Utilities  ... PoolArea PoolQC  Fence  \
0               Reg         Lvl    AllPub  ...        0    NaN    NaN   
1               Reg         Lvl    AllPub  ...        0    NaN    NaN   
2               IR1         Lvl    AllPub  ...        0    NaN    NaN   
3               IR1         Lvl    AllPub  ...        0    NaN    NaN   
4               IR1         Lvl    AllPub  ...        0    NaN    NaN   
...             ...         ...       ...  ...      ...    ...    ...   
2068            IR1         Lvl    AllPub  ...        0    NaN  GdPrv   
2069            IR1         Lvl    AllPub  ...        0    NaN    NaN   
2070            Reg         Low    AllPub  ...        0    NaN    NaN   
2071            IR1         Lvl    NoSeWa  ...        0    NaN    NaN   
2072            Reg         Lvl    AllPub  ...        0    NaN   MnWw   

     MiscFeature MiscVal MoSold YrSold  SaleType  SaleCondition  \
0            NaN       0      2   2008        WD         Normal   
1            NaN       0      5   2007        WD         Normal   
2            NaN       0      9   2008        WD         Normal   
3            NaN       0      2   2006        WD        Abnorml   
4            NaN       0     12   2008        WD         Normal   
...          ...     ...    ...    ...       ...            ...   
2068         NaN       0      6   2009        WD         Normal   
2069         NaN       0      8   2007       Oth        Abnorml   
2070         NaN       0      6   2007        WD         Normal   
2071         NaN       0      1   2009       COD        Abnorml   
2072         NaN       0      9   2009        WD         Normal   

      Property_Sale_Price  
0                  208500  
1                  181500  
2                  223500  
3                  140000  
4                  250000  
...                   ...  
2068               214000  
2069               150000  
2070               143000  
2071               137500  
2072               124900  

[2073 rows x 81 columns]

In [15]:
x=property_data[['LotArea','YearBuilt','OverallQual','OverallCond','BedroomAbvGr','KitchenAbvGr','LowQualFinSF','BsmtFinSF2','GarageCars','GarageArea','YrSold','PoolArea','FullBath','TotalBsmtSF','GrLivArea','ScreenPorch','HalfBath','BsmtFullBath','2ndFlrSF']]#independent

In [16]:
y=property_data['Property_Sale_Price']#dependent(output)

In [17]:
print(x)

      LotArea  YearBuilt  OverallQual  OverallCond  BedroomAbvGr  \
0        8450       2003            7            5             3   
1        9600       1976            6            8             3   
2       11250       2001            7            5             3   
3        9550       1915            7            5             3   
4       14260       2000            8            5             4   
...       ...        ...          ...          ...           ...   
2068     8755       1936            8            4             3   
2069     7711       1936            6            9             4   
2070    25000       1983            4            6             4   
2071    14375       1958            9            6             3   
2072     8820       1890            9            9             2   

      KitchenAbvGr  LowQualFinSF  BsmtFinSF2  GarageCars  GarageArea  YrSold  \
0                1             0           0           2         548    2008   
1                1     

In [18]:
print(y)

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
2068    214000
2069    150000
2070    143000
2071    137500
2072    124900
Name: Property_Sale_Price, Length: 2073, dtype: int64


In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
model=LinearRegression()

In [21]:
model.fit(x,y)

LinearRegression()

In [22]:
model.score(x,y)

0.7682307306892314

In [23]:
model.predict([[9874,1986,9,10,4,2,110,310,1,387,2000,0,2,999,1374,100,0,2,1000]])

array([148117.642739])

In [24]:
from sklearn.model_selection import train_test_split#import

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [26]:
model.fit(x_train,y_train)

LinearRegression()

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
lin_reg_mod=LinearRegression()

In [29]:
lin_reg_mod.fit(x_train,y_train)

LinearRegression()

In [30]:
pred=lin_reg_mod.predict(x_test)

In [31]:
pred

array([ 96318.96665059, 163600.39488778, 242981.34944226, 177266.80620281,
       103825.94594604, 178951.78908928, 106011.601313  , 220716.94351812,
       238514.47169032, 149845.81403285, 118720.96281732, 247694.2653479 ,
       310356.89267245, 180427.14232648, 225653.83677286, 258606.36282905,
       129660.98523861, 190954.50196215, 112930.31607639,  70007.90291278,
       211234.81118077, 200827.09240255, 129352.06825735, 195548.32606861,
       219127.92398765, 216869.98537777, 234848.6786444 ,  98388.98621064,
       245202.54916301, 149394.29853305, 273004.21711094, 205109.38317207,
       132412.0723919 , 268468.42930277, 158827.38627318, 128438.35964009,
       112214.75212179, 183135.89481149, 134289.66039284, 104225.43888874,
       216017.62546788, 152798.17115823, 139720.62740658,  62337.86559314,
       203914.01834649, 204461.06485121,  95551.92113496, 159281.83694928,
       109547.87965239, 211575.73664179,  88790.62647938, 241981.10506498,
       312833.35857558, 1

In [32]:
import numpy as np
from sklearn import metrics
test_set_r2=metrics.r2_score(y_test,pred)

In [33]:
print(test_set_r2)

0.7726026078828557


In [34]:
lin_reg_mod.predict([[9874,1986,9,10,4,2,110,310,1,387,2000,0,2,999,1374,100,0,2,1000]])

array([148462.70870764])

In [35]:
import seaborn as sb

In [36]:
model.coef_

array([ 2.60329399e-01,  2.84942373e+02,  4.29769811e+03,  3.57182228e+03,
       -9.70006934e+03, -4.48668529e+04, -4.86727397e+01, -1.96543734e+01,
        1.76202527e+04,  6.18749559e+00, -3.62574602e+02, -1.44707263e+02,
        1.42232376e+04,  3.30689396e+01,  7.92933955e+01,  5.31769016e+01,
        7.04436570e+03,  1.34500131e+04, -7.95257673e+00])